### ISSUE TITLE
bug: custom error not thrown on failed simulation

### ISSUE THREAD

**Issue by ubinatus** [wagmi-dev/viem#493]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

^0.3.22

### Current Behavior

Hello Team,

Something is going on with the custom solidity errors on the contract. When simulating the contract transaction (`publicClient.simulateContract`) that is expected to be reverted with a custom error, the thrown error doesn't contain data nor the expected error.

Right now, whenever a contract write call gets reverted with a custom solidity error, it simply throws an error without an indication of what's the specific error. There is no `data` as well. The latter could be used to decode the custom error with `decodeErrorResult`

### Expected Behavior

The expected (or desired) behaviour is to receive the custom solidity error or the error data (in order to decode it with `decodeErrorResult`) in case the simulated transaction actually get reverted with a custom solidity error.

### Steps To Reproduce

1. Open the attached stackblitz example
2. Open your developer console and see the logs of the simulation error -> There will be no specific indication of the custom solidity error

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://stackblitz.com/edit/viem-getting-started-kizhyl?file=index.ts

#### Current contract method
![image](https://github.com/wagmi-dev/viem/assets/51177379/2f9b9067-ef66-444a-abaf-0ac86d9e11bc)

#### Current error thrown on simulation
![image](https://github.com/wagmi-dev/viem/assets/51177379/5b10e7b7-9e45-4f2e-b165-05c98fc0f8fc)

#### Contract address
https://polygonscan.com/address/0xAB56176Ab5Bb06A6aE90e9E3EDEEDD683c4B09B6#code#F19#L213

**Comment by jxom** [comment]
Fixed!

**Comment by ubinatus** [comment]
That was fast! Thanks a lot @jxom ! So the custom error for now is found on the `err.metaMessages[0]`. Good

**Comment by jxom** [comment]
Yeah, good point, might be good to expose it as an attribute off the error instance, instead of extracting from the meta messages strings. Can look into that!

**Comment by ubinatus** [comment]
Sound good! I'm about to sleep but tomorrow morning that I have some time could help you with a PR for that issue. Will check in tomorrow in case it's not resolved  ☺️

**Comment by jxom** [comment]
Feel free! It will be quite trivial to add.

**Comment by emretepedev** [comment]
I'm trying to migrate from Ethers v6 to viem. Everything is going smoothly except for "Simulate." When I implement the same thing in Ethers, it gives the actual error, but in viem, it just says it's reverted without providing any details.

```ts
// ethers
const staticCallRes = await contract.transfer
  .staticCall(address.value, BigInt(1000000000000 * 10 ** 18))
  .then((res) => res)
  .catch((e) => e)

  if (staticCallRes instanceof Error) {
    console.log(staticCallRes.message)
  }

// viem
  const staticCallRes = await contract.simulate
    .transfer([address.value, BigInt(1000000000000 * 10 ** 18)])
    .then((res) => res)
    .catch((err) => err)

  if (staticCallRes instanceof Error) {
    console.log(staticCallRes.message)
  }
```
ethers' log:
```
execution reverted: ERC20InsufficientBalance(address,uint256,uint256)
```

viem' log:
```
The contract function "transfer" reverted.

Contract Call:
  address:   0xdcd0f1eB0Fdc6CDa180339323c7686321ff3F147
  function:  transfer(address to, uint256 value)
  args:              (0xa508dD875f10C33C52a8abb20E16fc68E981F186, 1000000000000000019884624838656)
  sender:    0xa508dD875f10C33C52a8abb20E16fc68E981F186

Docs: https://viem.sh/docs/contract/simulateContract
Version: viem@2.7.22
```
